[package]
name = "formica-ci"
version = "0.1.0"
authors = ["Daniel Gray"]
edition = "2018"

[dependencies]
ctrlc = "3.1.7"
crossbeam-channel = "0.5.0"
exitcode = "1.1.2"
env_logger = "0.8.1"
log = "0.4"
